// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: control.proto

package control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SFUControl_Connect_FullMethodName = "/control.SFUControl/Connect"
)

// SFUControlClient is the client API for SFUControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SFUControlClient interface {
	// The single bidirectional stream.
	// Both Client (SFU) and Server (Iris) use the `Message` type.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error)
}

type sFUControlClient struct {
	cc grpc.ClientConnInterface
}

func NewSFUControlClient(cc grpc.ClientConnInterface) SFUControlClient {
	return &sFUControlClient{cc}
}

func (c *sFUControlClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Message, Message], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SFUControl_ServiceDesc.Streams[0], SFUControl_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Message, Message]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SFUControl_ConnectClient = grpc.BidiStreamingClient[Message, Message]

// SFUControlServer is the server API for SFUControl service.
// All implementations must embed UnimplementedSFUControlServer
// for forward compatibility.
type SFUControlServer interface {
	// The single bidirectional stream.
	// Both Client (SFU) and Server (Iris) use the `Message` type.
	Connect(grpc.BidiStreamingServer[Message, Message]) error
	mustEmbedUnimplementedSFUControlServer()
}

// UnimplementedSFUControlServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSFUControlServer struct{}

func (UnimplementedSFUControlServer) Connect(grpc.BidiStreamingServer[Message, Message]) error {
	return status.Error(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedSFUControlServer) mustEmbedUnimplementedSFUControlServer() {}
func (UnimplementedSFUControlServer) testEmbeddedByValue()                    {}

// UnsafeSFUControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SFUControlServer will
// result in compilation errors.
type UnsafeSFUControlServer interface {
	mustEmbedUnimplementedSFUControlServer()
}

func RegisterSFUControlServer(s grpc.ServiceRegistrar, srv SFUControlServer) {
	// If the following call panics, it indicates UnimplementedSFUControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SFUControl_ServiceDesc, srv)
}

func _SFUControl_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SFUControlServer).Connect(&grpc.GenericServerStream[Message, Message]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SFUControl_ConnectServer = grpc.BidiStreamingServer[Message, Message]

// SFUControl_ServiceDesc is the grpc.ServiceDesc for SFUControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SFUControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "control.SFUControl",
	HandlerType: (*SFUControlServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _SFUControl_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "control.proto",
}
