// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: control.proto

package control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is the top-level wrapper that encapsulates every possible message.
// We have a single stream so every message must be of this type,
// We are using `oneof` to figure out what the actual payload is based on the payload type.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Message_JoinRoom
	//	*Message_LeaveRoom
	//	*Message_PublisherOffer
	//	*Message_SubscriberAnswer
	//	*Message_ClientPublisherIce
	//	*Message_ClientSubscriberIce
	//	*Message_PublisherAnswer
	//	*Message_SubscriberOffer
	//	*Message_SfuPublisherIce
	//	*Message_SfuSubscriberIce
	//	*Message_JoinRoomAck
	//	*Message_LeaveRoomAck
	//	*Message_MediaPublished
	//	*Message_MediaUnpublished
	//	*Message_SubscriberAnswerAck
	//	*Message_HealthPing
	Payload       isMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetPayload() isMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetJoinRoom() *JoinRoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_JoinRoom); ok {
			return x.JoinRoom
		}
	}
	return nil
}

func (x *Message) GetLeaveRoom() *LeaveRoomRequest {
	if x != nil {
		if x, ok := x.Payload.(*Message_LeaveRoom); ok {
			return x.LeaveRoom
		}
	}
	return nil
}

func (x *Message) GetPublisherOffer() *PublisherOffer {
	if x != nil {
		if x, ok := x.Payload.(*Message_PublisherOffer); ok {
			return x.PublisherOffer
		}
	}
	return nil
}

func (x *Message) GetSubscriberAnswer() *SubscriberAnswer {
	if x != nil {
		if x, ok := x.Payload.(*Message_SubscriberAnswer); ok {
			return x.SubscriberAnswer
		}
	}
	return nil
}

func (x *Message) GetClientPublisherIce() *ICECandidatePayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_ClientPublisherIce); ok {
			return x.ClientPublisherIce
		}
	}
	return nil
}

func (x *Message) GetClientSubscriberIce() *ICECandidatePayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_ClientSubscriberIce); ok {
			return x.ClientSubscriberIce
		}
	}
	return nil
}

func (x *Message) GetPublisherAnswer() *PublisherAnswer {
	if x != nil {
		if x, ok := x.Payload.(*Message_PublisherAnswer); ok {
			return x.PublisherAnswer
		}
	}
	return nil
}

func (x *Message) GetSubscriberOffer() *SubscriberOffer {
	if x != nil {
		if x, ok := x.Payload.(*Message_SubscriberOffer); ok {
			return x.SubscriberOffer
		}
	}
	return nil
}

func (x *Message) GetSfuPublisherIce() *ICECandidatePayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_SfuPublisherIce); ok {
			return x.SfuPublisherIce
		}
	}
	return nil
}

func (x *Message) GetSfuSubscriberIce() *ICECandidatePayload {
	if x != nil {
		if x, ok := x.Payload.(*Message_SfuSubscriberIce); ok {
			return x.SfuSubscriberIce
		}
	}
	return nil
}

func (x *Message) GetJoinRoomAck() *JoinRoomAck {
	if x != nil {
		if x, ok := x.Payload.(*Message_JoinRoomAck); ok {
			return x.JoinRoomAck
		}
	}
	return nil
}

func (x *Message) GetLeaveRoomAck() *LeaveRoomAck {
	if x != nil {
		if x, ok := x.Payload.(*Message_LeaveRoomAck); ok {
			return x.LeaveRoomAck
		}
	}
	return nil
}

func (x *Message) GetMediaPublished() *MediaPublishedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Message_MediaPublished); ok {
			return x.MediaPublished
		}
	}
	return nil
}

func (x *Message) GetMediaUnpublished() *MediaUnpublishedEvent {
	if x != nil {
		if x, ok := x.Payload.(*Message_MediaUnpublished); ok {
			return x.MediaUnpublished
		}
	}
	return nil
}

func (x *Message) GetSubscriberAnswerAck() *SubscriberAnswerAck {
	if x != nil {
		if x, ok := x.Payload.(*Message_SubscriberAnswerAck); ok {
			return x.SubscriberAnswerAck
		}
	}
	return nil
}

func (x *Message) GetHealthPing() *HealthPing {
	if x != nil {
		if x, ok := x.Payload.(*Message_HealthPing); ok {
			return x.HealthPing
		}
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_JoinRoom struct {
	// Iris -> SFU
	JoinRoom *JoinRoomRequest `protobuf:"bytes,1,opt,name=join_room,json=joinRoom,proto3,oneof"`
}

type Message_LeaveRoom struct {
	LeaveRoom *LeaveRoomRequest `protobuf:"bytes,2,opt,name=leave_room,json=leaveRoom,proto3,oneof"`
}

type Message_PublisherOffer struct {
	PublisherOffer *PublisherOffer `protobuf:"bytes,3,opt,name=publisher_offer,json=publisherOffer,proto3,oneof"`
}

type Message_SubscriberAnswer struct {
	SubscriberAnswer *SubscriberAnswer `protobuf:"bytes,4,opt,name=subscriber_answer,json=subscriberAnswer,proto3,oneof"`
}

type Message_ClientPublisherIce struct {
	ClientPublisherIce *ICECandidatePayload `protobuf:"bytes,5,opt,name=client_publisher_ice,json=clientPublisherIce,proto3,oneof"`
}

type Message_ClientSubscriberIce struct {
	ClientSubscriberIce *ICECandidatePayload `protobuf:"bytes,6,opt,name=client_subscriber_ice,json=clientSubscriberIce,proto3,oneof"`
}

type Message_PublisherAnswer struct {
	// SFU -> Iris
	PublisherAnswer *PublisherAnswer `protobuf:"bytes,7,opt,name=publisher_answer,json=publisherAnswer,proto3,oneof"`
}

type Message_SubscriberOffer struct {
	SubscriberOffer *SubscriberOffer `protobuf:"bytes,8,opt,name=subscriber_offer,json=subscriberOffer,proto3,oneof"`
}

type Message_SfuPublisherIce struct {
	SfuPublisherIce *ICECandidatePayload `protobuf:"bytes,9,opt,name=sfu_publisher_ice,json=sfuPublisherIce,proto3,oneof"`
}

type Message_SfuSubscriberIce struct {
	SfuSubscriberIce *ICECandidatePayload `protobuf:"bytes,10,opt,name=sfu_subscriber_ice,json=sfuSubscriberIce,proto3,oneof"`
}

type Message_JoinRoomAck struct {
	JoinRoomAck *JoinRoomAck `protobuf:"bytes,11,opt,name=join_room_ack,json=joinRoomAck,proto3,oneof"`
}

type Message_LeaveRoomAck struct {
	LeaveRoomAck *LeaveRoomAck `protobuf:"bytes,12,opt,name=leave_room_ack,json=leaveRoomAck,proto3,oneof"`
}

type Message_MediaPublished struct {
	MediaPublished *MediaPublishedEvent `protobuf:"bytes,13,opt,name=media_published,json=mediaPublished,proto3,oneof"`
}

type Message_MediaUnpublished struct {
	MediaUnpublished *MediaUnpublishedEvent `protobuf:"bytes,14,opt,name=media_unpublished,json=mediaUnpublished,proto3,oneof"`
}

type Message_SubscriberAnswerAck struct {
	SubscriberAnswerAck *SubscriberAnswerAck `protobuf:"bytes,15,opt,name=subscriber_answer_ack,json=subscriberAnswerAck,proto3,oneof"`
}

type Message_HealthPing struct {
	// SFU -> Iris
	// Status messages.
	HealthPing *HealthPing `protobuf:"bytes,16,opt,name=health_ping,json=healthPing,proto3,oneof"`
}

func (*Message_JoinRoom) isMessage_Payload() {}

func (*Message_LeaveRoom) isMessage_Payload() {}

func (*Message_PublisherOffer) isMessage_Payload() {}

func (*Message_SubscriberAnswer) isMessage_Payload() {}

func (*Message_ClientPublisherIce) isMessage_Payload() {}

func (*Message_ClientSubscriberIce) isMessage_Payload() {}

func (*Message_PublisherAnswer) isMessage_Payload() {}

func (*Message_SubscriberOffer) isMessage_Payload() {}

func (*Message_SfuPublisherIce) isMessage_Payload() {}

func (*Message_SfuSubscriberIce) isMessage_Payload() {}

func (*Message_JoinRoomAck) isMessage_Payload() {}

func (*Message_LeaveRoomAck) isMessage_Payload() {}

func (*Message_MediaPublished) isMessage_Payload() {}

func (*Message_MediaUnpublished) isMessage_Payload() {}

func (*Message_SubscriberAnswerAck) isMessage_Payload() {}

func (*Message_HealthPing) isMessage_Payload() {}

type SDPPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "offer" or "answer"
	Sdp           string                 `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SDPPayload) Reset() {
	*x = SDPPayload{}
	mi := &file_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SDPPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SDPPayload) ProtoMessage() {}

func (x *SDPPayload) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SDPPayload.ProtoReflect.Descriptor instead.
func (*SDPPayload) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{1}
}

func (x *SDPPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SDPPayload) GetSdp() string {
	if x != nil {
		return x.Sdp
	}
	return ""
}

type ICECandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidate     string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid        string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex int32                  `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICECandidate) Reset() {
	*x = ICECandidate{}
	mi := &file_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidate) ProtoMessage() {}

func (x *ICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidate.ProtoReflect.Descriptor instead.
func (*ICECandidate) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{2}
}

func (x *ICECandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *ICECandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *ICECandidate) GetSdpMlineIndex() int32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

type ICECandidatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Candidate     *ICECandidate          `protobuf:"bytes,3,opt,name=candidate,proto3" json:"candidate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ICECandidatePayload) Reset() {
	*x = ICECandidatePayload{}
	mi := &file_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ICECandidatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ICECandidatePayload) ProtoMessage() {}

func (x *ICECandidatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ICECandidatePayload.ProtoReflect.Descriptor instead.
func (*ICECandidatePayload) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{3}
}

func (x *ICECandidatePayload) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ICECandidatePayload) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ICECandidatePayload) GetCandidate() *ICECandidate {
	if x != nil {
		return x.Candidate
	}
	return nil
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{4}
}

func (x *JoinRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type JoinRoomAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomAck) Reset() {
	*x = JoinRoomAck{}
	mi := &file_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomAck) ProtoMessage() {}

func (x *JoinRoomAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomAck.ProtoReflect.Descriptor instead.
func (*JoinRoomAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{5}
}

func (x *JoinRoomAck) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *JoinRoomAck) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *JoinRoomAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *JoinRoomAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LeaveRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomRequest) Reset() {
	*x = LeaveRoomRequest{}
	mi := &file_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomRequest) ProtoMessage() {}

func (x *LeaveRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomRequest.ProtoReflect.Descriptor instead.
func (*LeaveRoomRequest) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{6}
}

func (x *LeaveRoomRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaveRoomRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type LeaveRoomAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveRoomAck) Reset() {
	*x = LeaveRoomAck{}
	mi := &file_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveRoomAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveRoomAck) ProtoMessage() {}

func (x *LeaveRoomAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveRoomAck.ProtoReflect.Descriptor instead.
func (*LeaveRoomAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveRoomAck) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *LeaveRoomAck) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LeaveRoomAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LeaveRoomAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PublisherOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Used to correlate the asynchronous response
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Sdp           *SDPPayload            `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherOffer) Reset() {
	*x = PublisherOffer{}
	mi := &file_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherOffer) ProtoMessage() {}

func (x *PublisherOffer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherOffer.ProtoReflect.Descriptor instead.
func (*PublisherOffer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{8}
}

func (x *PublisherOffer) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PublisherOffer) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PublisherOffer) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PublisherOffer) GetSdp() *SDPPayload {
	if x != nil {
		return x.Sdp
	}
	return nil
}

type SubscriberAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Sdp           *SDPPayload            `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriberAnswer) Reset() {
	*x = SubscriberAnswer{}
	mi := &file_control_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriberAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberAnswer) ProtoMessage() {}

func (x *SubscriberAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberAnswer.ProtoReflect.Descriptor instead.
func (*SubscriberAnswer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{9}
}

func (x *SubscriberAnswer) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubscriberAnswer) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubscriberAnswer) GetSdp() *SDPPayload {
	if x != nil {
		return x.Sdp
	}
	return nil
}

type SubscriberAnswerAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriberAnswerAck) Reset() {
	*x = SubscriberAnswerAck{}
	mi := &file_control_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriberAnswerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberAnswerAck) ProtoMessage() {}

func (x *SubscriberAnswerAck) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberAnswerAck.ProtoReflect.Descriptor instead.
func (*SubscriberAnswerAck) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{10}
}

func (x *SubscriberAnswerAck) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubscriberAnswerAck) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubscriberAnswerAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubscriberAnswerAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type PublisherAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Matches the request_id from PublisherOfferRequest
	RoomId        string                 `protobuf:"bytes,2,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Sdp           *SDPPayload            `protobuf:"bytes,4,opt,name=sdp,proto3" json:"sdp,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherAnswer) Reset() {
	*x = PublisherAnswer{}
	mi := &file_control_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherAnswer) ProtoMessage() {}

func (x *PublisherAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherAnswer.ProtoReflect.Descriptor instead.
func (*PublisherAnswer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{11}
}

func (x *PublisherAnswer) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PublisherAnswer) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PublisherAnswer) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *PublisherAnswer) GetSdp() *SDPPayload {
	if x != nil {
		return x.Sdp
	}
	return nil
}

func (x *PublisherAnswer) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublisherAnswer) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SubscriberOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Sdp           *SDPPayload            `protobuf:"bytes,3,opt,name=sdp,proto3" json:"sdp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriberOffer) Reset() {
	*x = SubscriberOffer{}
	mi := &file_control_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriberOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriberOffer) ProtoMessage() {}

func (x *SubscriberOffer) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriberOffer.ProtoReflect.Descriptor instead.
func (*SubscriberOffer) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{12}
}

func (x *SubscriberOffer) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *SubscriberOffer) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *SubscriberOffer) GetSdp() *SDPPayload {
	if x != nil {
		return x.Sdp
	}
	return nil
}

type MediaPublishedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Mid           string                 `protobuf:"bytes,3,opt,name=mid,proto3" json:"mid,omitempty"`
	PublisherId   string                 `protobuf:"bytes,4,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaPublishedEvent) Reset() {
	*x = MediaPublishedEvent{}
	mi := &file_control_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaPublishedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaPublishedEvent) ProtoMessage() {}

func (x *MediaPublishedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaPublishedEvent.ProtoReflect.Descriptor instead.
func (*MediaPublishedEvent) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{13}
}

func (x *MediaPublishedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MediaPublishedEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MediaPublishedEvent) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *MediaPublishedEvent) GetPublisherId() string {
	if x != nil {
		return x.PublisherId
	}
	return ""
}

type MediaUnpublishedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Mid           string                 `protobuf:"bytes,3,opt,name=mid,proto3" json:"mid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUnpublishedEvent) Reset() {
	*x = MediaUnpublishedEvent{}
	mi := &file_control_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUnpublishedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUnpublishedEvent) ProtoMessage() {}

func (x *MediaUnpublishedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUnpublishedEvent.ProtoReflect.Descriptor instead.
func (*MediaUnpublishedEvent) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{14}
}

func (x *MediaUnpublishedEvent) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *MediaUnpublishedEvent) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MediaUnpublishedEvent) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

type HealthPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SfuId         string                 `protobuf:"bytes,1,opt,name=sfu_id,json=sfuId,proto3" json:"sfu_id,omitempty"`
	CpuUsage      float32                `protobuf:"fixed32,2,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	ActiveRooms   int32                  `protobuf:"varint,3,opt,name=active_rooms,json=activeRooms,proto3" json:"active_rooms,omitempty"`
	StatusLabel   string                 `protobuf:"bytes,4,opt,name=status_label,json=statusLabel,proto3" json:"status_label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthPing) Reset() {
	*x = HealthPing{}
	mi := &file_control_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthPing) ProtoMessage() {}

func (x *HealthPing) ProtoReflect() protoreflect.Message {
	mi := &file_control_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthPing.ProtoReflect.Descriptor instead.
func (*HealthPing) Descriptor() ([]byte, []int) {
	return file_control_proto_rawDescGZIP(), []int{15}
}

func (x *HealthPing) GetSfuId() string {
	if x != nil {
		return x.SfuId
	}
	return ""
}

func (x *HealthPing) GetCpuUsage() float32 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *HealthPing) GetActiveRooms() int32 {
	if x != nil {
		return x.ActiveRooms
	}
	return 0
}

func (x *HealthPing) GetStatusLabel() string {
	if x != nil {
		return x.StatusLabel
	}
	return ""
}

var File_control_proto protoreflect.FileDescriptor

const file_control_proto_rawDesc = "" +
	"\n" +
	"\rcontrol.proto\x12\acontrol\"\x84\t\n" +
	"\aMessage\x127\n" +
	"\tjoin_room\x18\x01 \x01(\v2\x18.control.JoinRoomRequestH\x00R\bjoinRoom\x12:\n" +
	"\n" +
	"leave_room\x18\x02 \x01(\v2\x19.control.LeaveRoomRequestH\x00R\tleaveRoom\x12B\n" +
	"\x0fpublisher_offer\x18\x03 \x01(\v2\x17.control.PublisherOfferH\x00R\x0epublisherOffer\x12H\n" +
	"\x11subscriber_answer\x18\x04 \x01(\v2\x19.control.SubscriberAnswerH\x00R\x10subscriberAnswer\x12P\n" +
	"\x14client_publisher_ice\x18\x05 \x01(\v2\x1c.control.ICECandidatePayloadH\x00R\x12clientPublisherIce\x12R\n" +
	"\x15client_subscriber_ice\x18\x06 \x01(\v2\x1c.control.ICECandidatePayloadH\x00R\x13clientSubscriberIce\x12E\n" +
	"\x10publisher_answer\x18\a \x01(\v2\x18.control.PublisherAnswerH\x00R\x0fpublisherAnswer\x12E\n" +
	"\x10subscriber_offer\x18\b \x01(\v2\x18.control.SubscriberOfferH\x00R\x0fsubscriberOffer\x12J\n" +
	"\x11sfu_publisher_ice\x18\t \x01(\v2\x1c.control.ICECandidatePayloadH\x00R\x0fsfuPublisherIce\x12L\n" +
	"\x12sfu_subscriber_ice\x18\n" +
	" \x01(\v2\x1c.control.ICECandidatePayloadH\x00R\x10sfuSubscriberIce\x12:\n" +
	"\rjoin_room_ack\x18\v \x01(\v2\x14.control.JoinRoomAckH\x00R\vjoinRoomAck\x12=\n" +
	"\x0eleave_room_ack\x18\f \x01(\v2\x15.control.LeaveRoomAckH\x00R\fleaveRoomAck\x12G\n" +
	"\x0fmedia_published\x18\r \x01(\v2\x1c.control.MediaPublishedEventH\x00R\x0emediaPublished\x12M\n" +
	"\x11media_unpublished\x18\x0e \x01(\v2\x1e.control.MediaUnpublishedEventH\x00R\x10mediaUnpublished\x12R\n" +
	"\x15subscriber_answer_ack\x18\x0f \x01(\v2\x1c.control.SubscriberAnswerAckH\x00R\x13subscriberAnswerAck\x126\n" +
	"\vhealth_ping\x18\x10 \x01(\v2\x13.control.HealthPingH\x00R\n" +
	"healthPingB\t\n" +
	"\apayload\"2\n" +
	"\n" +
	"SDPPayload\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03sdp\x18\x02 \x01(\tR\x03sdp\"m\n" +
	"\fICECandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x03 \x01(\x05R\rsdpMlineIndex\"\x80\x01\n" +
	"\x13ICECandidatePayload\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x123\n" +
	"\tcandidate\x18\x03 \x01(\v2\x15.control.ICECandidateR\tcandidate\"G\n" +
	"\x0fJoinRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\x82\x01\n" +
	"\vJoinRoomAck\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"H\n" +
	"\x10LeaveRoomRequest\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\x83\x01\n" +
	"\fLeaveRoomAck\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\x8c\x01\n" +
	"\x0ePublisherOffer\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12%\n" +
	"\x03sdp\x18\x04 \x01(\v2\x13.control.SDPPayloadR\x03sdp\"o\n" +
	"\x10SubscriberAnswer\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12%\n" +
	"\x03sdp\x18\x03 \x01(\v2\x13.control.SDPPayloadR\x03sdp\"\x8a\x01\n" +
	"\x13SubscriberAnswerAck\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\"\xcc\x01\n" +
	"\x0fPublisherAnswer\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\aroom_id\x18\x02 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x03 \x01(\tR\bclientId\x12%\n" +
	"\x03sdp\x18\x04 \x01(\v2\x13.control.SDPPayloadR\x03sdp\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\"n\n" +
	"\x0fSubscriberOffer\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12%\n" +
	"\x03sdp\x18\x03 \x01(\v2\x13.control.SDPPayloadR\x03sdp\"\x80\x01\n" +
	"\x13MediaPublishedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\tR\x03mid\x12!\n" +
	"\fpublisher_id\x18\x04 \x01(\tR\vpublisherId\"_\n" +
	"\x15MediaUnpublishedEvent\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x10\n" +
	"\x03mid\x18\x03 \x01(\tR\x03mid\"\x86\x01\n" +
	"\n" +
	"HealthPing\x12\x15\n" +
	"\x06sfu_id\x18\x01 \x01(\tR\x05sfuId\x12\x1b\n" +
	"\tcpu_usage\x18\x02 \x01(\x02R\bcpuUsage\x12!\n" +
	"\factive_rooms\x18\x03 \x01(\x05R\vactiveRooms\x12!\n" +
	"\fstatus_label\x18\x04 \x01(\tR\vstatusLabel2?\n" +
	"\n" +
	"SFUControl\x121\n" +
	"\aConnect\x12\x10.control.Message\x1a\x10.control.Message(\x010\x01B\x19Z\x17proto-contracts/controlb\x06proto3"

var (
	file_control_proto_rawDescOnce sync.Once
	file_control_proto_rawDescData []byte
)

func file_control_proto_rawDescGZIP() []byte {
	file_control_proto_rawDescOnce.Do(func() {
		file_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)))
	})
	return file_control_proto_rawDescData
}

var file_control_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_control_proto_goTypes = []any{
	(*Message)(nil),               // 0: control.Message
	(*SDPPayload)(nil),            // 1: control.SDPPayload
	(*ICECandidate)(nil),          // 2: control.ICECandidate
	(*ICECandidatePayload)(nil),   // 3: control.ICECandidatePayload
	(*JoinRoomRequest)(nil),       // 4: control.JoinRoomRequest
	(*JoinRoomAck)(nil),           // 5: control.JoinRoomAck
	(*LeaveRoomRequest)(nil),      // 6: control.LeaveRoomRequest
	(*LeaveRoomAck)(nil),          // 7: control.LeaveRoomAck
	(*PublisherOffer)(nil),        // 8: control.PublisherOffer
	(*SubscriberAnswer)(nil),      // 9: control.SubscriberAnswer
	(*SubscriberAnswerAck)(nil),   // 10: control.SubscriberAnswerAck
	(*PublisherAnswer)(nil),       // 11: control.PublisherAnswer
	(*SubscriberOffer)(nil),       // 12: control.SubscriberOffer
	(*MediaPublishedEvent)(nil),   // 13: control.MediaPublishedEvent
	(*MediaUnpublishedEvent)(nil), // 14: control.MediaUnpublishedEvent
	(*HealthPing)(nil),            // 15: control.HealthPing
}
var file_control_proto_depIdxs = []int32{
	4,  // 0: control.Message.join_room:type_name -> control.JoinRoomRequest
	6,  // 1: control.Message.leave_room:type_name -> control.LeaveRoomRequest
	8,  // 2: control.Message.publisher_offer:type_name -> control.PublisherOffer
	9,  // 3: control.Message.subscriber_answer:type_name -> control.SubscriberAnswer
	3,  // 4: control.Message.client_publisher_ice:type_name -> control.ICECandidatePayload
	3,  // 5: control.Message.client_subscriber_ice:type_name -> control.ICECandidatePayload
	11, // 6: control.Message.publisher_answer:type_name -> control.PublisherAnswer
	12, // 7: control.Message.subscriber_offer:type_name -> control.SubscriberOffer
	3,  // 8: control.Message.sfu_publisher_ice:type_name -> control.ICECandidatePayload
	3,  // 9: control.Message.sfu_subscriber_ice:type_name -> control.ICECandidatePayload
	5,  // 10: control.Message.join_room_ack:type_name -> control.JoinRoomAck
	7,  // 11: control.Message.leave_room_ack:type_name -> control.LeaveRoomAck
	13, // 12: control.Message.media_published:type_name -> control.MediaPublishedEvent
	14, // 13: control.Message.media_unpublished:type_name -> control.MediaUnpublishedEvent
	10, // 14: control.Message.subscriber_answer_ack:type_name -> control.SubscriberAnswerAck
	15, // 15: control.Message.health_ping:type_name -> control.HealthPing
	2,  // 16: control.ICECandidatePayload.candidate:type_name -> control.ICECandidate
	1,  // 17: control.PublisherOffer.sdp:type_name -> control.SDPPayload
	1,  // 18: control.SubscriberAnswer.sdp:type_name -> control.SDPPayload
	1,  // 19: control.PublisherAnswer.sdp:type_name -> control.SDPPayload
	1,  // 20: control.SubscriberOffer.sdp:type_name -> control.SDPPayload
	0,  // 21: control.SFUControl.Connect:input_type -> control.Message
	0,  // 22: control.SFUControl.Connect:output_type -> control.Message
	22, // [22:23] is the sub-list for method output_type
	21, // [21:22] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_control_proto_init() }
func file_control_proto_init() {
	if File_control_proto != nil {
		return
	}
	file_control_proto_msgTypes[0].OneofWrappers = []any{
		(*Message_JoinRoom)(nil),
		(*Message_LeaveRoom)(nil),
		(*Message_PublisherOffer)(nil),
		(*Message_SubscriberAnswer)(nil),
		(*Message_ClientPublisherIce)(nil),
		(*Message_ClientSubscriberIce)(nil),
		(*Message_PublisherAnswer)(nil),
		(*Message_SubscriberOffer)(nil),
		(*Message_SfuPublisherIce)(nil),
		(*Message_SfuSubscriberIce)(nil),
		(*Message_JoinRoomAck)(nil),
		(*Message_LeaveRoomAck)(nil),
		(*Message_MediaPublished)(nil),
		(*Message_MediaUnpublished)(nil),
		(*Message_SubscriberAnswerAck)(nil),
		(*Message_HealthPing)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_proto_rawDesc), len(file_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_proto_goTypes,
		DependencyIndexes: file_control_proto_depIdxs,
		MessageInfos:      file_control_proto_msgTypes,
	}.Build()
	File_control_proto = out.File
	file_control_proto_goTypes = nil
	file_control_proto_depIdxs = nil
}
